ALTER TABLE users ADD COLUMN registered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE packages ADD COLUMN downloads INTEGER NOT NULL DEFAULT 0,
                     ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE likes (
    "user" INTEGER CONSTRAINT likes_user_fk REFERENCES users ON DELETE CASCADE,
    package TEXT CONSTRAINT likes_package_fk REFERENCES packages ON DELETE CASCADE,
    "time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT likes_pk PRIMARY KEY ("user", package)
);

ALTER TABLE versions ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE maintainers DROP CONSTRAINT maintains_package_fk;
ALTER TABLE maintainers ADD CONSTRAINT maintainers_package_fk FOREIGN KEY (package) REFERENCES packages
    ON DELETE CASCADE;