DROP TABLE dependency_descriptions;
DROP TABLE version_texts;
DROP TABLE descriptions;
DROP TABLE maintainers;
DROP TABLE dependencies;
DROP TABLE contents;
DROP TABLE versions;
DROP TABLE packages;
DROP TABLE users;